#!/bin/sh

torr_rmv=~/download/*.torrent

alias trdl='trash-put $torr_rmv'

alias eps='epson-printer-utility'  # утилита, показывающая уровень чернил и пр.

#    BACKUP

# restic
bkp_torrent=/mnt/ext-2Tb/bkp_torrent
bkp_data=/mnt/ext-2Tb/bkp_data
alias rbt='restic -r $bkp_torrent/backup-repo --verbose backup /mnt/torrent --exclude-file $exclude_torrent'
alias rbd='restic -r $bkp_data/backup-repo --verbose backup --files-from $bkp_data/list_bkp.txt --exclude-caches --exclude-file $bkp_data/excludes.txt'

# snapshots, unlock, check, prune, mount ~/restic, forget qw90j8ce, forget --keep-last 5 --prune
alias rt='restic -r $bkp_torrent/backup-repo'
alias rd='restic -r $bkp_data/backup-repo'
alias rj='restic -r /mnt/data/bkp/joplin/backup-repo'
alias rs='restic -r /mnt/sams25/backup-repo'


