#!/bin/sh

alias torr='trash-put ~/Загрузки/*.torrent'

#    BACKUP

# restic
bkp_job=/run/media/cs/Sams25
alias rbs='restic -r $bkp_job/backup-repo --verbose backup --files-from $bkp_job/list_bkp.txt --exclude-caches --exclude-file $bkp_job/excludes.txt'
alias rs-vm='rsync -avzh --delete-after /mnt/vm/Win10_luks $bkp_job/vm'
alias rbj='restic -r /mnt/data/sys/bkp/Joplin/backup-repo --verbose backup --password-file /mnt/data/sys/bkp/Joplin/passwd.txt /home/cs/.config/joplin-desktop/'
alias rbj-forget='restic -r /mnt/data/sys/bkp/Joplin/backup-repo forget --keep-last 20 --prune'

# snapshots, unlock, check, prune, mount ~/restic, forget qw90j8ce, forget --keep-last 5 --prune
alias rts='restic -r /run/media/cs/Sams25/backup-repo'
alias rtj='restic -r /mnt/data/sys/bkp/Joplin/backup-repo'
alias rtf='restic -r ./backup-repo forget --keep-last $1 --prune'

#    НАВИГАЦИЯ

alias cdy='cd /media/sf__shr/ytb' # для шары виртуальной машины


