#!/bin/sh

# cd ~/.aliases
# git pull --rebase
# git diff
# git log -p | less
# git add .
# git status
# git commit -m "comment"
# git push

# запустить команду без срабатывания алиаса - испз обрат слэш: \lsblk


# ................................   GIT    ................................ 


alias pull='echo "\n--- GIT ZSH ---" && cd ~/.aliases && git pull --rebase && cd && echo "\n--- YANDEX DISK ---" && yandex-disk status'
alias push='cd ~/.aliases; git diff; read; git add .; git commit -m "comment"; git push; cd'
# нажать q, потом enter
# read -p "Продолжить? (Y/N): " confirm && [[ $confirm == [yY] || $confirm == [yY][eE][sS] ]] || exit 1;




#  ................................   SSH    ................................ 


alias mount_inet='sshfs inet: ~/remote/inet'
alias mount_drweb='sshfs drweb: ~/remote/drweb'


# ................................   КРИПТО ПРО и cer   ................................   

cer () { for i in *.cer ; do
	 echo
	 openssl x509 -in "$i" -text -noout | sed 's/  */ /g' | awk '/Serial Number:/ {getline; print "sn  ", $0}' | sed 's/://g'
         openssl x509 -in "$i" -text -noout | grep -o 'CN=[^,]*' 
         openssl x509 -in "$i" -text -noout | grep -o 'Not Before[^,]*' 
         openssl x509 -in "$i" -text -noout | grep -o 'Not After[^,]*' 
         openssl x509 -in "$i" -text -noout | awk '/X509v3 CRL Distribution Points:/ {flag=1} /X509v3 Subject Key Identifier:/ {flag=0} flag' | sed 's/  */ /g'
	 echo 
	 echo
 done
 }


alias cdkey='cd /var/opt/cprocsp/keys/cs; ls'

cpkey () {
	folderkey=$1;  # короткое имя ; исходный каталог - каталог нахождения копируемого
	if [[ -d $folderkey ]]; 
	then	
		cp -r $folderkey /var/opt/cprocsp/keys/cs;
		cd /var/opt/cprocsp/keys/cs;
		chown -R cs:cs $folderkey;
		chmod 700 $folderkey;
		chmod 600 $folderkey/*;
		ls -lah;
		ls -lah $folderkey;
	else
		echo folderkey не задан или не существует;
	fi }


cer_rename () {
    for i in *.cer ; do

	TEXT_1=$(openssl x509 -in "$i" -text -noout | grep -o 'CN=[^,]*')
	TEXT_2=$(openssl x509 -in "$i" -text -noout | grep -m 1 -o 'Not After[^,]*')

	# Извлекаем вторую строку с CN= (пропускаем первую)
	FULL_NAME=$(echo "$TEXT_1" | sed '1d' | sed 's/CN=//')

	# Преобразуем ФИО в формат "Фамилия"
	SURNAME=$(echo "$FULL_NAME" | awk '{print $1}')

	# Извлекаем дату и форматируем в ГГГГ_ММ_ДД
	DATE_RAW=$(echo "$TEXT_2" | awk '{print $5, $4, $7}')
	DATE_FORMATTED=$(date -d "$DATE_RAW" +"%Y_%m_%d")

	# Формируем новое имя файла
	NEW_FILENAME="${SURNAME}_${DATE_FORMATTED}.cer"

	# Проверяем, чтобы не перезаписать существующий файл
	if [ -e "$NEW_FILENAME" ]; then
        	echo "Ошибка: файл $NEW_FILENAME уже существует. Пропускаем $i."
		continue
	fi

	# Переименовываем файл
	mv "$i" "$NEW_FILENAME"

	echo "Файл переименован в: $NEW_FILENAME"

    done
}



# ................................   СИСТЕМА   ................................ 
pfu () {
    PROXY_ADDR="socks5://127.0.0.1:2080"
    NO_PROXY="localhost,127.0.0.1,::1"

    echo "➡️ Активирован локальный прокси SOCKS5 на $PROXY_ADDR"

    # Основные переменные для всего трафика
    export all_proxy="$PROXY_ADDR"
    export ALL_PROXY="$PROXY_ADDR"

    # Также установим HTTP/HTTPS для совместимости с некоторыми старыми утилитами
    export http_proxy="$PROXY_ADDR"
    export HTTP_PROXY="$PROXY_ADDR"
    export https_proxy="$PROXY_ADDR"
    export HTTPS_PROXY="$PROXY_ADDR"

    # Исключения
    export no_proxy="$NO_PROXY"
    export NO_PROXY="$NO_PROXY"
}

jl_data() { journalctl --since "$1" }  # format "2012-10-30 18:17:16", можно дату без времени
cash_cl() { sudo sync && sudo sh -c 'echo 3 >/proc/sys/vm/drop_caches' }  # может зависнуть - sync наверняка не может сбросить данные кеша на носитель
alias sp='systemctl suspend'
alias rt='systemctl reboot'
alias eps='epson-printer-utility'  # утилита, показывающая уровень чернил и пр.
alias fontfc='sudo fc-cache -fv'   # установка шрифта (добавить в кэш)

alias lsblk='lsblk -o NAME,START,SIZE,TYPE,FSTYPE,ALIGNMENT,MOUNTPOINTS' # ALIGNMENT выравниевание (0 - есть выравнивание)


# ................................ files 

mkdir_gen () {
	for i in $(seq -w 1 15); do
		mkdir "$i"
		echo "Created directory: $i"
	done
}

# ................................ path to clipboard

alias ptoc='pwd | wl-copy'


# ................................ Flatpak

alias listfpak='flatpak list --app'


# ................................ dnf

alias ups='sudo dnf update'                    
alias ill='sudo dnf install'
rmv () { sudo dnf remove $1 && sudo dnf autoremove }
alias ilist='dnf list --installed | grep'
alias rlist='sudo dnf repolist'


# ................................ app others

alias vi='nvim'
alias yb='yandex-browser-stable --proxy-server="172.23.99.80:3128" --proxy-bypass-list="localhost,127.0.0.1,::1,172.16.0.0/12" > /dev/null 2>&1 & disown'


# ................................ systemd

alias srvst='sudo systemctl start backup_joplin.service'
alias drd='sudo systemctl daemon-reload'
alias srvss='systemctl status backup_joplin.service'


# ................................ user group

alias csg='cat /etc/group | grep cs'  # в каких группах состоит пользователь cs


# ................................ корзина

alias rmm='trash-put $1'
alias tordel='trash-put ~/download/*.torrent*'


# ................................ rename

rname_date () {
    for file in *; do
        if [[ -f "$file" ]]; then
	    newname=$(date -r "$file" +"%Y-%m-%d_%H-%M-%S")
            mv "$file" "${newname}.${file##*.}"
        fi
    done
}


trname () { echo $1 | tr ' ' '_' | wl-copy }

alias name='rename -av " " "_" * ; rename -av "__" "_" *'

# к имени каталога добавляет точку
# испз только для переименования файлов, потому как если и каталогов то файлы уже не найдет, т.к. каталог переименован будет
rname () {
	# Директория для поиска (по умолчанию текущая) - функция принимает её в качестве внешнего аргумента
	SEARCH_DIR=${1:-.}

	# Обработка всех файлов в директории
	find "$SEARCH_DIR" -type f | while read -r FILE; do
	    # Извлекаем директорию, имя файла и расширение
	    DIRNAME=$(dirname "$FILE")
	    BASENAME=$(basename "$FILE")
	    EXTENSION="${BASENAME##*.}"       # Расширение файла
	    FILENAME="${BASENAME%.*}"         # Имя файла без расширения

	    # Если файл без расширения, обрабатываем как есть
	    if [[ "$FILENAME" == "$BASENAME" ]]; then
	        NEW_FILENAME=$(echo "$FILENAME" | sed -e 's/[^[:alpha:]^[:digit:]-]/_/g' | sed -e 's/__/_/g')
	        NEW_BASENAME="$NEW_FILENAME"
	    else
	        # Заменяем символы в имени файла, сохраняя расширение
	        NEW_FILENAME=$(echo "$FILENAME" | sed -e 's/[^[:alpha:]^[:digit:]-]/_/g' | sed -e 's/__/_/g')
	        NEW_BASENAME="$NEW_FILENAME.$EXTENSION"
	    fi

	    # Если имя изменилось, переименовываем
	    if [ "$BASENAME" != "$NEW_BASENAME" ]; then
	        mv "$FILE" "$DIRNAME/$NEW_BASENAME"
	        echo "Renamed: $FILE -> $DIRNAME/$NEW_BASENAME"
	    fi
	done
}


rname_find () {
	# Директория для поиска (по умолчанию текущая)
	SEARCH_DIR=${1:-.}

	# Поиск файлов с "[skl]" в имени и переименование
	find "$SEARCH_DIR" -type f -name '*[skladchik.org]*' | while read -r FILE; do
		# Новое имя файла
		NEW_NAME=$(echo "$FILE" | sed 's/\[skladchik.org\] //g')
    
    		# Переименование файла
    		mv "$FILE" "$NEW_NAME"
    		echo "Renamed: $FILE -> $NEW_NAME"
	done
}


# ................................ config

alias alg='alias | grep $1'
alias all='less ~/.aliases/main'
alias ala='less ~/.aliases/arc'
alias alv='less ~/.aliases/vs'
alias ale='less ~/.aliases/edit'
alias alled='nvim ~/.aliases/main' 
alias alaed='nvim ~/.aliases/arc' 
alias alved='nvim ~/.aliases/vs' 
alias aleed='nvim ~/.aliases/edit'
alias src='source ~/.zshrc'

# ................................ Size

# вычисляет и выводит размеры файлов и каталогов в рабочей директории
alias dfsys='btrfs filesystem df /'   # для btrfs на системном
alias ussys='sudo btrfs filesystem usage /'  # подробнее, но от рута запускать надо

# Пользоваться ncdu
alias duone='du -sch * | sort -h'  # размер каталогов первого уровня
# wildcard то работает то нет : alias duone='du -sch .[!.]* * |sort -h'
alias duhome='du -sh /home'  # размер домашнего каталога в Гб; если добавить -m или -k - в Мб или Кб
alias dusort='du -d 1 -h | sort -h'  # сортировка по размеру каталогов
# отфильтровать маленькие файлы, остальные сортировать по размеру; +G - в выводе тяжелее 1 Гб
alias dusortf='du -h /home | grep "^\s*[0-9\.]\+M" | sort -rn' 

# ................................ man yandex-disk : stop, start, publish, unpublish

alias yk='yandex-disk status'
alias ykr='yandex-disk stop && yandex-disk start'


# ................................ ls

alias l='ls -F'
alias la='ls -F -a'
alias ll='ls -F -lh'
alias lah='ls -F -lah'
alias tre='ls -T'


# ................................ history

alias h='history' # в zsh команда history выводит по-умолчанию 20 последних (history 20)
alias hg='history 0 | grep $1'



# ................................   PYTHON   ................................ 


alias py='python3'
# pip --version; ups; pip list; обновить пакет $1
alias pipup='pip install --user -U $1'


# ................................ job

alias cdoleg='cd /run/user/1000/gvfs/smb-share:server=172.18.18.3,share=share/Distribu/_Upload_/Oleg'

alias stoppcscd='sudo systemctl stop pcscd.socket && sudo systemctl stop pcscd' # остановка демона смарт-карт


# ................................   NET   ................................ 


alias whis='curl cli.fyi/$1' # whis -> whois - сервис - см. закладка на github

alias sited='wget --mirror -p --convert-links -P . $1'
    # wget --mirror -p --convert-links -P /home/dan xyz.com
    # -p загрузка всех файлов, необходимых для отображения страниц
    # --convert-links: ссылки будут преобразованы для локального просмотра сайта
    # -P /home/dan: материалы будут сохранены в папку /home/dan

alias flush='sudo systemd-resolve --flush-caches'



# ................................   КОНВЕРТАЦИИ   ................................ 


# список исходных кодировок iconv -l, в команде работает tab, чтобы не опечататься
# узнать кондировку - file file.txt или file -i file.txt ; второе почему-то не распознало ASCII
alias wintoutf='iconv -f WINDOWS-1251 -t UTF-8 -o $1 $2'   # $1 - out file, $2 - input file
winutf() { mkdir conv; for f in *.txt; do iconv -f WINDOWS-1251 -t UTF-8 -o conv/$f $f;  done }

# перекодировка имён файлов
alias fnametoutf='for file in *; do mv "$file" "`echo $file | iconv -f WINDOWS-1251 -t UTF-8`"; done'

alias mdtoepub='pandoc -f markdown -t epub nerd_.txt -o nerd.epub'

# ................................   BACKUP   ................................ 


# ................................ sync KnowBase 
dir_script=/home/cs/sys/script
dir_bkp=/home/cs/Dropbox/bkp

alias bp_kb='sh $dir_script/app-bkp.sh'

ync() {
    if [ -f "$dir_script/home.flag" ]; then   # home.flag - флага хоста
       restic -r $dir_bkp/appj --password-file $dir_script/app-repo.pwd restore latest:/home/cs/app/app_data --exclude-file $dir_script/app-exclude.lst --delete --target /home/cs/app/app_data
    elif [ -f "$dir_script/job.flag" ]; then
       restic -r $dir_bkp/apph --password-file $dir_script/app-repo.pwd restore latest:/home/cs/app/app_data --exclude-file $dir_script/app-exclude.lst --delete --target /home/cs/app/app_data
    fi
}

nap() {
    echo &&
    if pgrep -x dropbox >/dev/null; then
        echo "      DROPBOX STATUS" && echo &&      
        dropbox status
    else
        echo "DROPBOX НЕ ЗАПУЩЕН. ЗАПУСКАЮ..."
        dropbox start
    fi &&
    echo && echo "------------------------------------------------" && 
    echo && echo  "      HOME REPO" && \
    restic -r $dir_bkp/apph --password-file $dir_script/app-repo.pwd snapshots | tail -14 | awk '{print $1, $2, $3}' | sed -n '2p;6p;10p' &&
    echo && echo "\n      JOB REPO" && \
    restic -r $dir_bkp/appj --password-file $dir_script/app-repo.pwd snapshots | tail -14 | awk '{print $1, $2, $3}' | sed -n '2p;6p;10p'
}


alias repo_h='restic -r $dir_bkp/apph --password-file $dir_script/app-repo.pwd'
alias repo_j='restic -r $dir_bkp/appj --password-file $dir_script/app-repo.pwd'

alias log_h='less +G $dir_bkp/bkp_app_h.log'
alias log_j='less +G $dir_bkp/bkp_app_j.log'

alias diff_pwd='diff -r . ~/app/app_data/org/roam'
alias diff_latest='diff -r ~/sys/restic/snapshots/latest/home/cs/app/app_data/org/roam ~/app/app_data/org/roam'

# find . -mtime 0 - показать измененые файлы за последние сутки

# ................................ home

bp_torrent=/mnt/ext2Tb/bp_torrent
bp_data=/mnt/ext2Tb/bp_data

alias bp_data='restic -r $bp_data/data_repo --password-file $dir_script/home-bkp-repo.pwd --verbose backup --files-from $bp_data/list_bp.txt --exclude-caches --exclude-file $bp_data/excludes.txt'
alias bp_torr='rsync -avh --delete --log-file=$bp_torrent/rsync.log --exclude-from=$bp_torrent/excludes.txt /mnt/torrent $bp_torrent'

bp_vm() { 
    # rm -rf /mnt/ext_1Tb_25/bp_vm/* &&
    rsync -avh --delete --log-file=/mnt/ext_1Tb_25/bp_vm/rsync.log /mnt/vm/vm/ /mnt/ext_1Tb_25/bp_vm/
}

# snapshots, unlock, check, prune, mount ~/restic, forget id_snap, forget --keep-last 5 --prune
alias do_data='restic -r $bp_data/data_repo --password-file $dir_script/home-bkp-repo.pwd'
alias foget_data='restic -r /$bp_data/data_repo --password-file $dir_script/home-bkp-repo.pwd forget --keep-last 20 --prune'


# ................................ job

diryk_bkp=/mnt/data/y-dk/dbs/bkp

bp_job() {
   yandex-disk stop
   restic -r $diryk_bkp/job --password-file $dir_script/app-repo.pwd --verbose backup --files-from $diryk_bkp/job/list_bp.txt --exclude-caches --exclude-file $diryk_bkp/job/excludes.txt
   yandex-disk start
}

# добавить /home/cs/.config/libvirt - сохранённые состояния машин
#   ???   alias rsync_vmj='rsync -avzh --delete-after /mnt/vm/gnome-boxes ...../vm'

# snapshots, unlock, check, prune, mount ~/sys/restic, forget id_snap, forget --keep-last 5 --prune
alias do_job='restic -r $diryk_bkp/job --password-file $dir_script/app-repo.pwd'
alias forget_job='restic -r $diryk_bkp/job --password-file $dir_script/app-repo.pwd forget --keep-last 20 --prune'



# ................................   TLDR   ................................

tldr_my() { sed -n "/$1/,/$1_end/p" ~/app/app_data/Obsidian/Linux/tldr.md }
