#!/bin/sh

# cd ~/.aliases
# git pull --rebase
# git diff
# git log -p | less
# git add .
# git status
# git commit -m "comment"
# git push



# ................................   GIT    ................................ 


alias pull='cd ~/.aliases; git pull --rebase; cd'
alias push='cd ~/.aliases; git diff; read; git add .; git commit -m "comment"; git push; cd'
# нажать q, потом enter
# read -p "Продолжить? (Y/N): " confirm && [[ $confirm == [yY] || $confirm == [yY][eE][sS] ]] || exit 1;




#  ................................   SSH    ................................ 


alias mount_inet='sshfs inet: ~/remote/inet'
alias mount_drweb='sshfs drweb: ~/remote/drweb'


# ................................   КРИПТО ПРО   ................................   


alias cdkey='cd /var/opt/cprocsp/keys/cs; ls'

cpkey () {
	folderkey=$1;  # короткое имя ; исходный каталог - каталог нахождения копируемого
	if [[ -d $folderkey ]]; 
	then	
		cp -r $folderkey /var/opt/cprocsp/keys/cs;
		cd /var/opt/cprocsp/keys/cs;
		chown -R cs:cs $folderkey;
		chmod 700 $folderkey;
		chmod 600 $folderkey/*;
		ls -lah;
		ls -lah $folderkey;
	else
		echo folderkey не задан или не существует;
	fi }



# ................................   СИСТЕМА   ................................ 

jl_data() { journalctl --since "$1" }
cash_cl() { sudo sync && sudo sh -c 'echo 3 >/proc/sys/vm/drop_caches' }  # может зависнуть - sync наверняка не может сбросить данные кеша на носитель
alias sp='systemctl suspend'
alias rt='systemctl reboot'
alias eps='epson-printer-utility'  # утилита, показывающая уровень чернил и пр.


# ................................ path to clipboard

alias ptoc='pwd | wl-copy'


# ................................ Flatpak

alias listfpak='flatpak list --app'


# ................................ dnf

alias ups='sudo dnf update'                    
alias ill='sudo dnf install'
alias rmv='sudo dnf remove $1 && sudo dnf autoremove'
alias ilist='dnf list installed | grep'
alias rlist='sudo dnf repolist'


# ................................ app others

alias vi='nvim'


# ................................ systemd

alias srvst='sudo systemctl start backup_joplin.service'
alias drd='sudo systemctl daemon-reload'
alias srvss='systemctl status backup_joplin.service'


# ................................ user group

alias csg='cat /etc/group | grep cs'  # в каких группах состоит пользователь cs


# ................................ корзина

alias rmm='trash-put $1'
alias tordel='trash-put ~/download/*.torrent'


# ................................ rename

alias trname='echo $1 | tr ' ' '_' | wl-copy'

alias name='rename -av " " "_" * ; rename -av "__" "_" *'

# к имени каталога добавляет точку - ПРАВИТЬ !!!
rname () {
	for file in *
	do
		# Rename the file, leaving only letters and digits
		name=$(basename "$file" | sed 's/.[^.]*$//')
		extension=$(echo ${file##*.})
		new_name=$(echo "$name"| sed -e 's/[^[:alpha:]^[:digit:]-]/_/g' | sed -e 's/__/_/g')
		mv "$file" "$new_name.$extension"

		# Display a message that the file has been renamed successfully
		echo "File renamed to $new_name.$extension"
	done
}


# ................................ config

alias al='alias | bat'
alias all='bat ~/.aliases/main'
alias ala='bat ~/.aliases/arc'
alias alv='bat ~/.aliases/vs'
alias alled='nvim ~/.aliases/main' 
alias alaed='nvim ~/.aliases/arc' 
alias alved='nvim ~/.aliases/vs' 
alias alssh='bat ~/.ssh/config' # псевдонимы для ssh подключений
alias alp='alias -p'
alias src='source ~/.zshrc'


# ................................ Size

# вычисляет и выводит размеры файлов и каталогов в рабочей директории
alias dfsys='btrfs filesystem df /'   # для btrfs на системном
alias ussys='sudo btrfs filesystem usage /'  # подробнее, но от рута запускать надо

# Пользоваться ncdu
alias duone='du -sch * | sort -h'  # размер каталогов первого уровня
# wildcard то работает то нет : alias duone='du -sch .[!.]* * |sort -h'
alias duhome='du -sh /home'  # размер домашнего каталога в Гб; если добавить -m или -k - в Мб или Кб
alias dusort='du -d 1 -h | sort -h'  # сортировка по размеру каталогов
# отфильтровать маленькие файлы, остальные сортировать по размеру; +G - в выводе тяжелее 1 Гб
alias dusortf='du -h /home | grep "^\s*[0-9\.]\+M" | sort -rn' 

# ................................ man yandex-disk : stop, start, publish, unpublish

alias yk='yandex-disk status'
alias ykr='yandex-disk stop && yandex-disk start'


# ................................ ls

alias l='ls -CF'
alias ll='ls -l'
alias la='ls -a'
alias lah='ls -lah'


# ................................ history

alias h='history' # в zsh команда history выводит по-умолчанию 20 последних (history 20)
alias hg='history 0 | grep $1'



# ................................   PYTHON   ................................ 


alias py='python3'
# pip --version; ups; pip list; обновить пакет $1
alias pipup='pip install --user -U $1'



# ................................   НАВИГАЦИЯ   ................................ 


alias cd_yt-dlp-job='cd /media/sf__shr/ytb' # для шары виртуальной машины
alias cd_yt-dlp-home='cd /mnt/data/tmp/yt-dlp'
alias cda='cd ~/.aliases'


# ................................ job

alias cdoleg='cd /run/user/1000/gvfs/smb-share:server=172.18.18.3,share=share/Distribu/_Upload_/Oleg'



# ................................   NET   ................................ 


alias whis='curl cli.fyi/$1' # whis -> whois - сервис - см. закладка на github

alias sited='wget --mirror -p --convert-links -P . $1'
    # wget --mirror -p --convert-links -P /home/dan xyz.com
    # -p загрузка всех файлов, необходимых для отображения страниц
    # --convert-links: ссылки будут преобразованы для локального просмотра сайта
    # -P /home/dan: материалы будут сохранены в папку /home/dan

alias flush='sudo systemd-resolve --flush-caches'



# ................................   КОНВЕРТАЦИИ   ................................ 


# список исходных кодировок iconv -l, в команде работает tab, чтобы не опечататься
# узнать кондировку - file file.txt или file -i file.txt ; второе почему-то не распознало ASCII
alias wintoutf='iconv -f WINDOWS-1251 -t UTF-8 -o $1 $2'   # $1 - out file, $2 - input file

# перекодировка имён файлов
alias fnametoutf='for file in *; do mv "$file" "`echo $file | iconv -f WINDOWS-1251 -t UTF-8`"; done'

alias mdtoepub='pandoc -f markdown -t epub nerd_.txt -o nerd.epub'

# ................................   BACKUP   ................................ 


# ................................ home

bp_torrent=/mnt/ext2Tb/bp_torrent
bp_data=/mnt/ext2Tb/bp_data

alias restic_data='restic -r $bp_data/data_repo --verbose backup --files-from $bp_data/list_bp.txt --exclude-caches --exclude-file $bp_data/excludes.txt'
alias rsync_torrent='rsync -avh --delete-after --log-file=$bp_torrent/rsync.log --exclude-from=$bp_torrent/excludes.txt /mnt/torrent $bp_torrent'
alias rsync_vmh='rsync -avh --delete-after --log-file=/mnt/ext2Tb/bp_vm/rsync.log /mnt/vm/gnome-boxes /mnt/vm/vbox /mnt/ext2Tb/bp_vm'

# snapshots, unlock, check, prune, mount ~/restic, forget id_snap, forget --keep-last 5 --prune
alias restic_data_do='restic -r $bp_data/data_repo'
alias restic_data-forget='restic -r /$bp_data/data_repo forget --keep-last 20 --prune'


# ................................ job

bp_job=/mnt/data/y-dk/job/bp

restic-job() {
   yandex-disk stop
   restic -r $bp_job --verbose backup --files-from $bp_job/list_bp.txt --exclude-caches --exclude-file $bp_job/excludes.txt
   yandex-disk start
}

# добавить /home/cs/.config/libvirt - сохранённые состояния машин
#   ???   alias rsync_vmj='rsync -avzh --delete-after /mnt/vm/gnome-boxes ...../vm'

# snapshots, unlock, check, prune, mount ~/sys/restic, forget id_snap, forget --keep-last 5 --prune
alias restic_job_do='restic -r $bp_job'
alias restic_job-forget='restic -r $bp_job forget --keep-last 20 --prune'



# ................................   TLDR   ................................

tldr_my() { sed -n "/$1/,/$1_end/p" ~/app/app_data/Obsidian/Linux/tldr.md }
