#!/bin/sh

# cd ~/.aliases
# git pull --rebase
# git diff
# git add .
# git status
# git commit -m "comment"
# git push


#    КРИПТО ПРО
alias cdkey='cd /mnt/data/c-kv/key/Crypto\ Pro; ls -lah'
alias cdhdimg='cd /var/opt/cprocsp/keys/cs'

cpkey () {
	folderkey=$1;  # короткое имя ; исходный каталог - каталог нахождения копируемого
	if [[ -z $folderkey && -a $folderkey]]; then
		echo folderkey не задан
	else
		cp -r $folderkey /var/opt/cprocsp/keys/cs;
		cd /var/opt/cprocsp/keys/cs;
		chown -R cs:cs $folderkey;
		chmod 700 $folderkey;
		chmod 600 $folderkey/*;
		ls -lah;
		ls -lah $folderkey; 
	fi }

#    GIT

alias pull='cd ~/.aliases; git pull --rebase; cd'
alias push='cd ~/.aliases; git add .; git commit -m "comment"; git push; cd'

#    СИСТЕМА

alias sp='systemctl suspend'
alias rt='systemctl reboot'
alias eps='epson-printer-utility'  # утилита, показывающая уровень чернил и пр.

# dnf
alias ups='sudo dnf update'                    
alias ill='sudo dnf install'
alias rmv='sudo dnf remove $1 && sudo dnf autoremove'
alias lil='dnf list installed | grep'

# app others
alias joplin_up='wget -O - https://raw.githubusercontent.com/laurent22/joplin/dev/Joplin_install_and_update.sh | bash'

# systemd
alias srvst='sudo systemctl start backup_joplin.service'
alias drd='sudo systemctl daemon-reload'
alias srvss='systemctl status backup_joplin.service'

# user group
alias csg='cat /etc/group | grep cs'  # в каких группах состоит пользователь cs

# корзина
alias rmm='trash-put $1'
alias trdl='trash-put ~/download/*.torrent'

# rename
alias name='rename -a " " "_" *'

# config
alias al='alias | bat'
alias all='bat ~/.aliases/main'
alias ala='bat ~/.aliases/arc'
alias alv='bat ~/.aliases/vs'
alias alled='nvim ~/.aliases/main' 
alias alaed='nvim ~/.aliases/arc' 
alias alved='nvim ~/.aliases/vs' 
alias alssh='bat ~/.ssh/config' # псевдонимы для ssh подключений
alias alp='alias -p'
alias src='source ~/.bashrc'

# Size

# вычисляет и выводит размеры файлов и каталогов в рабочей директории
alias dfsys='btrfs filesystem df /'   # для btrfs на системном
alias ussys='sudo btrfs filesystem usage /'  # подробнее, но от рута запускать надо

# Пользоваться ncdu
alias duone='du -sch .[!.]* * |sort -h'  # размер каталогов первого уровня
alias duhome='du -sh /home'  # размер домашнего каталога в Гб; если добавить -m или -k - в Мб или Кб
alias dusort='du -d 1 -h | sort -h'  # сортировка по размеру каталогов
# отфильтровать маленькие файлы, остальные сортировать по размеру; +G - в выводе тяжелее 1 Гб
alias dusortf='du -h /home | grep '^\s*[0-9\.]\+M' | sort -rn' 

# man yandex-disk - на русском: stop, start, publish, unpublish
alias yk='yandex-disk status'

alias l='ls -CF'
alias ll='ls -l'
alias la='ls -a'
alias lah='ls -lah'

alias h='tail ~/.bash_history'
alias hg='history | grep $1'

#    PYTHON

alias py='python3'
# pip --version; ups; pip list; обновить пакет $1
alias pipup='pip install --user -U $1'

#    НАВИГАЦИЯ

alias cdy='cd /media/sf__shr/ytb' # для шары виртуальной машины
alias cda='cd ~/.aliases'

#    NET

alias whis='curl cli.fyi/$1' # whis -> whois - сервис - см. закладка на github

alias sited='wget --mirror -p --convert-links -P'
    # wget --mirror -p --convert-links -P /home/dan xyz.com
    # -p загрузка всех файлов, необходимых для отображения страниц
    # --convert-links: ссылки будут преобразованы для локального просмотра сайта
    # -P /home/dan: материалы будут сохранены в папку /home/dan

alias flush='sudo systemd-resolve --flush-caches'


#    КОНВЕРТАЦИИ

# список исходных кодировок iconv -l, в команде работает tab, чтобы не опечататься
# узнать кондировку - file file.txt или file -i file.txt ; второе почему-то не распознало ASCII
alias wintoutf='iconv -f WINDOWS-1251 -t UTF-8 -o $1 $2'   # $1 - out file, $2 - input file

#    BACKUP

# restic
bkp_torrent=/mnt/ext-2Tb/bkp_torrent
bkp_data=/mnt/ext-2Tb/bkp_data
alias rbt='restic -r $bkp_torrent/backup-repo --verbose backup /mnt/torrent --exclude-file $exclude_torrent'
alias rbd='restic -r $bkp_data/backup-repo --verbose backup --files-from $bkp_data/list_bkp.txt --exclude-caches --exclude-file $bkp_data/excludes.txt'

# snapshots, unlock, check, prune, mount ~/restic, forget qw90j8ce, forget --keep-last 5 --prune
alias rt='restic -r $bkp_torrent/backup-repo'
alias rd='restic -r $bkp_data/backup-repo'
alias rj='restic -r /mnt/data/bkp/joplin/backup-repo'
alias rs='restic -r /mnt/sams25/backup-repo'

# restic
bkp_job=/run/media/cs/Sams25
alias rbs='restic -r $bkp_job/backup-repo --verbose backup --files-from $bkp_job/list_bkp.txt --exclude-caches --exclude-file $bkp_job/excludes.txt'
alias rs-vm='rsync -avzh --delete-after /mnt/vm/ $bkp_job/vm'
alias rbj='restic -r /mnt/data/sys/bkp/Joplin/backup-repo --verbose backup --password-file /mnt/data/sys/bkp/Joplin/passwd.txt /home/cs/.config/joplin-desktop/'
alias rbj-forget='restic -r /mnt/data/sys/bkp/Joplin/backup-repo forget --keep-last 20 --prune'

# snapshots, unlock, check, prune, mount ~/restic, forget qw90j8ce, forget --keep-last 5 --prune
alias rts='restic -r $bkp_job/backup-repo'
alias rtj='restic -r /mnt/data/sys/bkp/Joplin/backup-repo'
alias rtf='restic -r ./backup-repo forget --keep-last $1 --prune'

